[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[env]
TERM = "xterm-256color"
TERM_PROGRAM = "alacritty"

[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 18
